import type { ChatData } from "../../types";
import { formatCurrency, formatDateTime, productionReference } from "../../utils/format";

export function ChatStructuredData({ data }: { data: ChatData }) {
  const hasRecords = Boolean(data.alarms?.length || data.alarm_patterns?.length || data.telemetry?.length || data.maintenance_tickets?.length || data.orders?.length || data.quotes?.length || data.maintenance_observation);
  if (!hasRecords) return null;
  return <section className="chat-data" aria-label="Retrieved records">
    {data.alarms && data.alarms.length > 0 && <article className="chat-data-card"><h4>Recent alarms</h4><div className="chat-data-table-wrap"><table><thead><tr><th>Date</th><th>Code</th><th>Severity</th><th>Status</th></tr></thead><tbody>{data.alarms.map((alarm) => <tr key={alarm.alarm_id}><td>{formatDateTime(alarm.timestamp)}</td><td>{alarm.alarm_code}</td><td>{alarm.severity}</td><td>{alarm.alarm_status}</td></tr>)}</tbody></table></div></article>}
    {data.alarm_patterns && data.alarm_patterns.length > 0 && <article className="chat-data-card"><h4>Repeated alarm conditions</h4><div className="chat-data-table-wrap"><table><thead><tr><th>Code</th><th>Occurrences</th><th>First seen</th><th>Last seen</th><th>Latest status</th></tr></thead><tbody>{data.alarm_patterns.map((pattern) => <tr key={pattern.alarm_code}><td>{pattern.alarm_code}</td><td>{pattern.occurrences}</td><td>{formatDateTime(pattern.first_seen)}</td><td>{formatDateTime(pattern.last_seen)}</td><td>{pattern.latest_status}</td></tr>)}</tbody></table></div></article>}
    {data.telemetry && data.telemetry.length > 0 && <article className="chat-data-card"><h4>Latest telemetry</h4><div className="chat-data-table-wrap"><table><thead><tr><th>Date</th><th>Status</th><th>Production</th><th>Reference</th><th>Uptime</th><th>Temp.</th></tr></thead><tbody>{data.telemetry.map((entry) => <tr key={entry.timestamp}><td>{formatDateTime(entry.timestamp)}</td><td>{entry.operational_status}</td><td>{entry.production_rate_bph.toLocaleString("en-GB")} bph</td><td title={entry.production_assessment?.reason}>{productionReference(entry)}</td><td>{entry.uptime_percentage}%</td><td>{entry.temperature_c ?? "—"}{entry.temperature_c !== null ? " °C" : ""}</td></tr>)}</tbody></table></div></article>}
    {data.maintenance_tickets && data.maintenance_tickets.length > 0 && <article className="chat-data-card"><h4>Maintenance tickets</h4><div className="chat-data-table-wrap"><table><thead><tr><th>Date</th><th>Ticket</th><th>Priority</th><th>Status</th></tr></thead><tbody>{data.maintenance_tickets.map((ticket) => <tr key={ticket.ticket_id}><td>{formatDateTime(ticket.created_date)}</td><td>{ticket.ticket_id}</td><td>{ticket.priority}</td><td>{ticket.ticket_status}</td></tr>)}</tbody></table></div></article>}
    {data.orders && data.orders.length > 0 && <article className="chat-data-card"><h4>Orders</h4><div className="chat-data-table-wrap"><table><thead><tr><th>Order</th><th>Status</th><th>Shipment</th></tr></thead><tbody>{data.orders.map((order) => <tr key={order.order_id}><td>{order.order_id}</td><td>{order.order_status}</td><td>{order.shipment_status}</td></tr>)}</tbody></table></div></article>}
    {data.quotes && data.quotes.length > 0 && <article className="chat-data-card"><h4>Quotes</h4><div className="chat-data-table-wrap"><table><thead><tr><th>Quote</th><th>Revision</th><th>Validity</th><th>Total</th></tr></thead><tbody>{data.quotes.map((quote) => <tr key={quote.quote_id}><td>{quote.quote_id}</td><td>{quote.revision_status ?? "—"}</td><td>{quote.validity_status}</td><td>{formatCurrency(quote.line_total)}</td></tr>)}</tbody></table></div></article>}
    {data.maintenance_observation && <article className="chat-data-card"><h4>Maintenance observation</h4><p>{data.maintenance_observation.observed_productive_hours.toLocaleString("en-GB")} productive hours observed{data.maintenance_observation.first_snapshot && data.maintenance_observation.last_snapshot ? ` from ${formatDateTime(data.maintenance_observation.first_snapshot)} to ${formatDateTime(data.maintenance_observation.last_snapshot)}` : " in the available telemetry window"}.</p><p>Thresholds reached: {data.maintenance_observation.reached_threshold_hours.length > 0 ? data.maintenance_observation.reached_threshold_hours.map((threshold) => `${threshold} h`).join(", ") : "none"}. Next threshold: {data.maintenance_observation.next_threshold_hours === null ? "not documented" : `${data.maintenance_observation.next_threshold_hours} h`}.</p><p>{data.maintenance_observation.scope_note}</p></article>}
  </section>;
}
