import { useState } from "react";
import type { FormEvent } from "react";
import { apiGet, fetchManualPdf, readableError } from "../../api/client";
import type { ManualSearchResult } from "../../types";
import { manualRelevanceLabel } from "../../utils/format";
import { useNotifications } from "../layout/Notifications";

export function ManualSearch({ machineId }: { machineId: string }) {
  const [query, setQuery] = useState(""); const [results, setResults] = useState<ManualSearchResult[]>([]); const [error, setError] = useState(""); const [hasSearched, setHasSearched] = useState(false); const [isSearching, setIsSearching] = useState(false); const [openingResult, setOpeningResult] = useState<number | null>(null); const { notify } = useNotifications();
  async function searchManual(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const normalizedQuery = query.trim(); if (!normalizedQuery || isSearching) return; setError(""); setIsSearching(true); setHasSearched(true); try { const loadedResults = await apiGet<ManualSearchResult[]>(`/machines/${encodeURIComponent(machineId)}/manuals/search?query=${encodeURIComponent(normalizedQuery)}&limit=5`); setResults(loadedResults); } catch (searchError) { const message = readableError(searchError, "Unable to search the manual."); setResults([]); setError(message); notify(message, "error"); } finally { setIsSearching(false); } }
  async function openManual(result: ManualSearchResult, index: number) {
    // Opening the tab synchronously keeps this action permitted by browser popup protection; the protected PDF is loaded into it afterwards.
    const manualWindow = window.open("", "_blank"); if (!manualWindow) { const message = "Your browser blocked the new tab. Allow pop-ups for this site and try again."; setError(message); notify(message, "error"); return; }
    setError(""); setOpeningResult(index); try { const pdf = await fetchManualPdf(machineId, result.citation.file); const pdfUrl = URL.createObjectURL(pdf); manualWindow.location.href = `${pdfUrl}#page=${result.citation.page}`; window.setTimeout(() => URL.revokeObjectURL(pdfUrl), 60_000); notify(`Opening ${result.citation.file} at page ${result.citation.page}.`, "success"); } catch (openError) { manualWindow.close(); const message = readableError(openError, "Unable to open the manual."); setError(message); notify(message, "error"); } finally { setOpeningResult(null); }
  }
  return <section className="manual-search" aria-labelledby="manual-search-title"><div><p className="eyebrow dark-eyebrow">TECHNICAL MANUALS</p><h2 id="manual-search-title">Search this machine's manuals</h2><p>Results come exclusively from local manuals associated with {machineId}.</p></div><form className="manual-search-form" onSubmit={searchManual}><label className="sr-only" htmlFor="manual-query">Search the manual</label><input id="manual-query" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="E.g. safety instructions or pneumatic pressure" disabled={isSearching} /><button type="submit" disabled={isSearching || !query.trim()}>{isSearching ? "Searching…" : "Search"}</button></form>{error && <p className="status-message error-message">{error}</p>}{hasSearched && !isSearching && !error && results.length === 0 && <p className="status-message">No relevant passage was found in this machine's manual.</p>}{results.length > 0 && <div className="manual-results" aria-live="polite">{results.map((result, index) => <article className="manual-result" key={`${result.citation.file}-${result.citation.page}-${index}`}><div className="manual-result-summary"><h3>{result.title}</h3><span className="manual-relevance">{manualRelevanceLabel(result.relevance)}</span></div><div className="manual-citation"><div><strong>{result.citation.file}</strong><span>Page {result.citation.page} · {result.citation.section}</span></div><button type="button" className="open-manual-button" onClick={() => openManual(result, index)} disabled={openingResult !== null}>{openingResult === index ? "Opening…" : `Open at page ${result.citation.page}`}</button></div><p>{result.excerpt}</p>{result.highlights.length > 0 && <div className="manual-highlights" aria-label="Matched terms"><span>Matched terms</span>{result.highlights.map((term) => <mark key={term}>{term}</mark>)}</div>}</article>)}</div>}</section>;
}
