import { useEffect, useState } from "react";
import { apiGet, readableError } from "../../api/client";
import type { AlarmRecord, MaintenanceTicketRecord, TelemetryRecord } from "../../types";
import { formatDateTime, productionReference } from "../../utils/format";
import { useNotifications } from "../layout/Notifications";

export function OperationalData({ machineId }: { machineId: string }) {
  const [alarms, setAlarms] = useState<AlarmRecord[]>([]); const [telemetry, setTelemetry] = useState<TelemetryRecord[]>([]); const [tickets, setTickets] = useState<MaintenanceTicketRecord[]>([]); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const { notify } = useNotifications();
  useEffect(() => {
    let isCurrent = true; setLoading(true); setError("");
    Promise.all([apiGet<AlarmRecord[]>(`/machines/${encodeURIComponent(machineId)}/alarms?limit=5`), apiGet<TelemetryRecord[]>(`/machines/${encodeURIComponent(machineId)}/telemetry?limit=6`), apiGet<MaintenanceTicketRecord[]>(`/machines/${encodeURIComponent(machineId)}/maintenance-tickets?limit=5`)]).then(([loadedAlarms, loadedTelemetry, loadedTickets]) => { if (!isCurrent) return; setAlarms(loadedAlarms); setTelemetry(loadedTelemetry); setTickets(loadedTickets); }).catch((loadError: unknown) => { if (!isCurrent) return; const message = readableError(loadError, "Unable to load operational data."); setError(message); notify(message, "error"); }).finally(() => { if (isCurrent) setLoading(false); });
    return () => { isCurrent = false; };
  }, [machineId, notify]);
  return <section className="operational-data" aria-labelledby="operational-data-title"><p className="eyebrow dark-eyebrow">OPERATIONAL DATA</p><h2 id="operational-data-title">Machine operational status</h2>{loading && <p className="status-message">Loading telemetry, alarms and maintenance data…</p>}{error && <p className="status-message error-message">{error}</p>}{!loading && !error && <div className="operational-grid"><article className="data-panel"><h3>Recent telemetry</h3>{telemetry.length === 0 ? <p className="data-empty">No telemetry available.</p> : <div className="data-table-wrap"><table><thead><tr><th>Date</th><th>Status</th><th>Production</th><th>Reference</th><th>Uptime</th><th>Temp.</th></tr></thead><tbody>{telemetry.map((entry) => <tr key={entry.timestamp}><td>{formatDateTime(entry.timestamp)}</td><td>{entry.operational_status}</td><td>{entry.production_rate_bph.toLocaleString("en-GB")} bph</td><td title={entry.production_assessment?.reason}>{productionReference(entry)}</td><td>{entry.uptime_percentage}%</td><td>{entry.temperature_c ?? "—"}{entry.temperature_c !== null ? " °C" : ""}</td></tr>)}</tbody></table></div>}</article><article className="data-panel"><h3>Recent alarms</h3>{alarms.length === 0 ? <p className="data-empty">No recent alarms.</p> : <div className="data-table-wrap"><table><thead><tr><th>Date</th><th>Code</th><th>Severity</th><th>Status</th></tr></thead><tbody>{alarms.map((alarm) => <tr key={alarm.alarm_id}><td>{formatDateTime(alarm.timestamp)}</td><td>{alarm.alarm_code}</td><td><span className={`severity severity-${alarm.severity.toLowerCase()}`}>{alarm.severity}</span></td><td>{alarm.alarm_status}</td></tr>)}</tbody></table></div>}</article><article className="data-panel data-panel-wide"><h3>Maintenance tickets</h3>{tickets.length === 0 ? <p className="data-empty">No maintenance tickets available.</p> : <div className="data-table-wrap"><table><thead><tr><th>ID</th><th>Opening date</th><th>Type</th><th>Priority</th><th>Status</th><th>Owner</th></tr></thead><tbody>{tickets.map((ticket) => <tr key={ticket.ticket_id}><td>{ticket.ticket_id}</td><td>{formatDateTime(ticket.created_date)}</td><td>{ticket.ticket_type}</td><td>{ticket.priority}</td><td>{ticket.ticket_status}</td><td>{ticket.owner_role}</td></tr>)}</tbody></table></div>}</article></div>}</section>;
}
