import { useState } from "react";
import type { FormEvent } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import { ApiError, publicPost, readableError } from "../api/client";
import { storeSession } from "../auth/session";
import { useNotifications } from "../components/layout/Notifications";
import type { LoginResponse } from "../types";

export function LoginPage({ qrValue: routeQrValue }: { qrValue?: string }) {
  const navigate = useNavigate(); const location = useLocation(); const { notify } = useNotifications(); const [userId, setUserId] = useState(() => localStorage.getItem("arol.user-id") ?? ""); const [password, setPassword] = useState(""); const [error, setError] = useState(() => { const notice = sessionStorage.getItem("arol.session-notice") ?? ""; sessionStorage.removeItem("arol.session-notice"); return notice; }); const [isSubmitting, setIsSubmitting] = useState(false); const queryQrValue = new URLSearchParams(location.search).get("qr")?.trim(); const qrValue = routeQrValue ?? queryQrValue;
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const normalizedUserId = userId.trim().toUpperCase(); if (!normalizedUserId) { setError("Enter your user ID."); return; } if (password.length < 8) { setError("The password must contain at least 8 characters."); return; } setIsSubmitting(true); try { const session = await publicPost<LoginResponse>("/auth/login", { user_id: normalizedUserId, password }); storeSession(session.user.user_id, session.access_token); notify(`Signed in as ${session.user.user_id}.`, "success"); navigate(qrValue ? `/machines/${encodeURIComponent(qrValue)}` : "/home"); } catch (loginError) { const message = loginError instanceof ApiError && loginError.status === 401 ? "Invalid credentials. Check your details and try again." : readableError(loginError, "Unable to sign in."); setError(message); notify(message, "error"); } finally { setIsSubmitting(false); } }
  return <main className="login-layout"><section className="brand-panel" aria-label="AROL Customer Platform"><div className="brand-mark" aria-hidden="true">A</div><p className="eyebrow">AROL CUSTOMER PLATFORM</p><h1>The intelligent digital ecosystem for your machine fleet.</h1><p className="brand-copy">Access IoT telemetry, maintenance schedules, technical manuals, and AI-powered support for your equipment.</p></section><section className="login-panel"><form className="login-card" onSubmit={submit} noValidate><p className="eyebrow">AUTHENTICATION</p><h2>Welcome</h2><p className="login-intro">Enter your identifier to access the platform.</p>{qrValue && <p className="qr-context" role="status">Machine detected: <strong>{qrValue}</strong></p>}<label htmlFor="user-id">User ID</label><input id="user-id" name="user-id" autoComplete="username" placeholder="E.g. USR-001" value={userId} onChange={(event) => { setUserId(event.target.value); setError(""); }} aria-describedby={error ? "user-id-error" : "user-id-help"} />{error ? <p id="user-id-error" className="field-error" role="alert">{error}</p> : <p id="user-id-help" className="field-help">Enter your user ID and password.</p>}<label htmlFor="password">Password</label><input id="password" name="password" type="password" autoComplete="current-password" value={password} onChange={(event) => { setPassword(event.target.value); setError(""); }} minLength={8} required /><button type="submit" disabled={isSubmitting}>{isSubmitting ? "Signing in..." : "Log in"} <span aria-hidden="true">→</span></button></form></section></main>;
}
