import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { apiGet, readableError } from "../api/client";
import { RecordsLayout } from "../components/layout/RecordsLayout";
import { useNotifications } from "../components/layout/Notifications";
import type { MachineSummary, MaintenanceTicketRecord, OrderDetail, OrderRecord, QuoteHistory, QuoteRecord, ServiceTicket, UserProfile } from "../types";
import { formatCurrency, formatDateTime } from "../utils/format";

export function OrdersPage() {
  const [orders, setOrders] = useState<OrderRecord[]>([]); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const { notify } = useNotifications(); const navigate = useNavigate();
  useEffect(() => { apiGet<OrderRecord[]>("/orders").then(setOrders).catch((loadError: unknown) => { const message = readableError(loadError, "Unable to load orders."); setError(message); notify(message, "error"); }).finally(() => setLoading(false)); }, [notify]);
  return <RecordsLayout eyebrow="ORDERS" title="Your orders" intro="Review order, shipment, approved quote content and fulfilment." loading={loading} error={error} empty={orders.length === 0 ? "No orders available." : undefined}><div className="records-table-wrap"><table className="records-table"><thead><tr><th>Order</th><th>Quote</th><th>Order status</th><th>Shipment</th><th></th></tr></thead><tbody>{orders.map((order) => <tr key={order.order_id}><td>{order.order_id}</td><td>{order.quote_id}</td><td>{order.order_status}</td><td>{order.shipment_status}</td><td><button type="button" className="records-link" onClick={() => navigate(`/orders/${encodeURIComponent(order.order_id)}`)}>Details</button></td></tr>)}</tbody></table></div></RecordsLayout>;
}

export function OrderDetailPage() {
  const { orderId } = useParams(); const navigate = useNavigate(); const { notify } = useNotifications(); const [order, setOrder] = useState<OrderDetail | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  useEffect(() => { if (!orderId) return; apiGet<OrderDetail>(`/orders/${encodeURIComponent(orderId)}`).then(setOrder).catch((loadError: unknown) => { const message = readableError(loadError, "Unable to load order details."); setError(message); notify(message, "error"); }).finally(() => setLoading(false)); }, [orderId, notify]);
  return <RecordsLayout eyebrow="ORDER DETAILS" title={order?.order_id ?? "Order details"} intro="Order content is taken from the approved quote revision; fulfilment is tracked separately." loading={loading} error={error} empty={!loading && !error && !order ? "Order not found." : undefined}>{order && <><button className="back-link" type="button" onClick={() => navigate("/orders")}>← All orders</button><p className="page-intro">Quote {order.quote_id} · order {order.order_status} · shipment {order.shipment_status}</p><section className="operational-grid" aria-label="Order details"><article className="data-panel"><h3>Approved quote revision</h3>{order.approved_revision ? <p>Revision {order.approved_revision.revision_number} · {order.approved_revision.revision_status} · discount {order.approved_revision.discount_rate === null ? "—" : `${(order.approved_revision.discount_rate * 100).toLocaleString("en-GB")}%`}</p> : <p className="data-empty">No approved quote revision is available for this order.</p>}</article><article className="data-panel"><h3>Fulfilment</h3>{order.fulfillment.length === 0 ? <p className="data-empty">No fulfilment lines are available.</p> : <div className="data-table-wrap"><table><thead><tr><th>Line</th><th>Status</th></tr></thead><tbody>{order.fulfillment.map((line) => <tr key={line.order_line_id}><td>{line.order_line_id}</td><td>{line.fulfillment_status}</td></tr>)}</tbody></table></div>}</article><article className="data-panel data-panel-wide"><h3>Ordered content</h3>{order.items.length === 0 ? <p className="data-empty">No items are available from the approved quote revision.</p> : <div className="data-table-wrap"><table><thead><tr><th>Description</th><th>Machine</th><th>Net price</th></tr></thead><tbody>{order.items.map((item) => <tr key={item.quote_line_id}><td>{item.description ?? "—"}</td><td>{item.machine_id ?? "—"}</td><td>{formatCurrency(item.price, order.currency ?? "EUR")}</td></tr>)}</tbody></table></div>}</article></section></>}</RecordsLayout>;
}

export function ProfilePage() {
  const [profile, setProfile] = useState<UserProfile | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const { notify } = useNotifications();
  useEffect(() => { apiGet<UserProfile>("/profile").then(setProfile).catch((loadError: unknown) => { const message = readableError(loadError, "Unable to load your profile."); setError(message); notify(message, "error"); }).finally(() => setLoading(false)); }, [notify]);
  return <RecordsLayout eyebrow="PROFILE" title={profile ? `${profile.first_name} ${profile.last_name}` : "Your profile"} intro="Your account, permission scope and company information." loading={loading} error={error} empty={!loading && !error && !profile ? "Profile not found." : undefined}>{profile && <section className="operational-grid" aria-label="Profile details"><article className="data-panel"><h3>Account</h3><p><strong>{profile.job_title}</strong><br />{profile.email}<br />User ID: {profile.user_id}</p></article><article className="data-panel"><h3>Access scope</h3><p><strong>{profile.visibility}</strong><br />Company ID: {profile.company_id}</p></article><article className="data-panel data-panel-wide"><h3>Company</h3><p><strong>{profile.company_name}</strong><br />{profile.city}, {profile.country} · {profile.sector}<br />Currency: {profile.currency} · Locale: {profile.locale}</p></article></section>}</RecordsLayout>;
}

export function QuotesPage() {
  const [quotes, setQuotes] = useState<QuoteRecord[]>([]); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const { notify } = useNotifications(); const navigate = useNavigate();
  useEffect(() => { apiGet<QuoteRecord[]>("/quotes").then(setQuotes).catch((loadError: unknown) => { const message = readableError(loadError, "Unable to load quotes."); setError(message); notify(message, "error"); }).finally(() => setLoading(false)); }, [notify]);
  return <RecordsLayout eyebrow="QUOTES" title="Quotes" intro="Review quote revisions, validity, discounts and totals." loading={loading} error={error} empty={quotes.length === 0 ? "No quotes available." : undefined}><div className="records-table-wrap"><table className="records-table"><thead><tr><th>Quote</th><th>Revision</th><th>Status</th><th>Valid until</th><th>Validity</th><th>Discount</th><th>Total</th><th></th></tr></thead><tbody>{quotes.map((quote) => <tr key={quote.quote_id}><td>{quote.quote_id}</td><td>{quote.revision_number ?? "—"}</td><td>{quote.revision_status ?? "—"}</td><td>{quote.valid_until ? formatDateTime(quote.valid_until) : "—"}</td><td>{quote.validity_status}</td><td>{quote.discount_rate === null ? "—" : `${(quote.discount_rate * 100).toLocaleString("en-GB")}%`}</td><td>{formatCurrency(quote.line_total)}</td><td><button type="button" className="records-link" onClick={() => navigate(`/quotes/${encodeURIComponent(quote.quote_id)}`)}>History</button></td></tr>)}</tbody></table></div></RecordsLayout>;
}

export function QuoteHistoryPage() {
  const { quoteId } = useParams(); const navigate = useNavigate(); const { notify } = useNotifications(); const [history, setHistory] = useState<QuoteHistory | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  useEffect(() => { if (!quoteId) return; apiGet<QuoteHistory>(`/quotes/${encodeURIComponent(quoteId)}`).then(setHistory).catch((loadError: unknown) => { const message = readableError(loadError, "Unable to load quote history."); setError(message); notify(message, "error"); }).finally(() => setLoading(false)); }, [quoteId, notify]);
  return <RecordsLayout eyebrow="QUOTE HISTORY" title={history?.quote_id ?? "Quote history"} intro={history?.description ?? "Review revisions, quoted lines and changes."} loading={loading} error={error} empty={!loading && !error && !history ? "Quote not found." : undefined}>{history && <><button className="back-link" type="button" onClick={() => navigate("/quotes")}>← All quotes</button><p className="page-intro">Created {history.created_at ? formatDateTime(history.created_at) : "—"} · valid until {history.valid_until ? formatDateTime(history.valid_until) : "—"} · {history.validity_status}</p><section className="operational-grid" aria-label="Latest revision comparison"><article className="data-panel data-panel-wide"><h3>Latest revision changes</h3>{history.latest_comparison.length === 0 ? <p className="data-empty">No changed lines compared with the preceding revision.</p> : <div className="data-table-wrap"><table><thead><tr><th>Change</th><th>Description</th><th>Machine</th><th>Previous price</th><th>Current price</th></tr></thead><tbody>{history.latest_comparison.map((change, index) => <tr key={`${change.change}-${change.description}-${index}`}><td>{change.change.replace("_", " ")}</td><td>{change.description ?? "—"}</td><td>{change.machine_id ?? "—"}</td><td>{change.previous_price === null ? "—" : formatCurrency(change.previous_price, history.currency ?? "EUR")}</td><td>{change.current_price === null ? "—" : formatCurrency(change.current_price, history.currency ?? "EUR")}</td></tr>)}</tbody></table></div>}</article></section><section className="operational-grid" aria-label="Quote revisions">{history.revisions.map((revision) => <article className="data-panel data-panel-wide" key={revision.quote_revision_id}><h3>Revision {revision.revision_number} · {revision.revision_status}</h3><p>{revision.issued_at ? formatDateTime(revision.issued_at) : "Date unavailable"} · Discount {revision.discount_rate === null ? "—" : `${(revision.discount_rate * 100).toLocaleString("en-GB")}%`} · Total {formatCurrency(revision.line_total, history.currency ?? "EUR")}</p>{revision.change_summary && <p>{revision.change_summary}</p>}<div className="data-table-wrap"><table><thead><tr><th>Description</th><th>Machine</th><th>Net price</th></tr></thead><tbody>{revision.lines.map((line) => <tr key={line.quote_line_id}><td>{line.description ?? "—"}</td><td>{line.machine_id ?? "—"}</td><td>{formatCurrency(line.price, history.currency ?? "EUR")}</td></tr>)}</tbody></table></div></article>)}</section></>}</RecordsLayout>;
}

export function ServicePage() {
  const [tickets, setTickets] = useState<ServiceTicket[]>([]); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const { notify } = useNotifications();
  useEffect(() => { let isCurrent = true; apiGet<MachineSummary[]>("/machines").then(async (machines) => { const ticketGroups = await Promise.all(machines.map(async (machine) => { const machineTickets = await apiGet<MaintenanceTicketRecord[]>(`/machines/${encodeURIComponent(machine.machine_id)}/maintenance-tickets?limit=20`); return machineTickets.map((ticket) => ({ ...ticket, machine_id: machine.machine_id, serial_number: machine.serial_number })); })); if (isCurrent) setTickets(ticketGroups.flat().sort((first, second) => second.created_date.localeCompare(first.created_date))); }).catch((loadError: unknown) => { if (!isCurrent) return; const message = readableError(loadError, "Unable to load support tickets."); setError(message); notify(message, "error"); }).finally(() => { if (isCurrent) setLoading(false); }); return () => { isCurrent = false; }; }, [notify]);
  return <RecordsLayout eyebrow="AFTER-SALES SERVICE" title="After-sales support" intro="Review maintenance tickets for your company's machines." loading={loading} error={error} empty={tickets.length === 0 ? "No support tickets available." : undefined}><div className="records-table-wrap"><table className="records-table"><thead><tr><th>Ticket</th><th>Machine</th><th>Date</th><th>Type</th><th>Priority</th><th>Status</th><th>Owner</th></tr></thead><tbody>{tickets.map((ticket) => <tr key={`${ticket.machine_id}-${ticket.ticket_id}`}><td>{ticket.ticket_id}</td><td>{ticket.machine_id}<small>Serial {ticket.serial_number}</small></td><td>{formatDateTime(ticket.created_date)}</td><td>{ticket.ticket_type}</td><td>{ticket.priority}</td><td>{ticket.ticket_status}</td><td>{ticket.owner_role}</td></tr>)}</tbody></table></div></RecordsLayout>;
}
